/* ========================================================================
 * Copyright 2014 olorcito
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 olorcito

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_memberModel'], function() {
    App.Model.MemberModel = App.Model._MemberModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            if(!attrs.name){
                validationMessage += "The name can't be empty. ";
            }
            if(!attrs.firstName){
                validationMessage += "The first name can't be empty. ";
            }
            if(!attrs.lastName){
                validationMessage += "The last name can't be empty. ";
            }
            if(!attrs.docNumber){
                validationMessage += "The document number can't be empty. ";
            }
            if(!attrs.documenttypeId){
                validationMessage += "The document type id can't be empty. ";
            }
            if(!attrs.partnerId){
                validationMessage += "The partner id can't be empty. ";
            }
            if(attrs.docNumber.length<4){
                validationMessage += "The document numer must have at least 5 characters. ";
            }
            if(attrs.documenttypeId==='ninguno'){
                validationMessage += "The document type id must be specified. ";
            }
            var param = attrs.birthDate.split('/');
            var dia = param[0];
            var mes = param[1];
            var ano = param[2];
            var dat = new Date();
            dat.setFullYear(ano,mes-1,dia);
            var act = new Date();
            if(dat>=act){
                validationMessage += "The birth date must be valid. ";
            }
            act = act.getFullYear();
            if(dat<act){
                validationMessage += "The age must be less than 100 years. ";
            }
            return validationMessage;
        }

    });

    App.Model.MemberList = App.Model._MemberList.extend({
        model: App.Model.MemberModel
    });

    return  App.Model.MemberModel;

});